### ISSUE TITLE
1.7.0-rc1 adapter not initialized

### ISSUE THREAD

**Issue by tylkomat** [angular-ui/ui-scroll#170]
I use ui-scroll together with ui-router. After updating now from a half year old version I noticed that the adapter is not working as expected anymore.

## List view

    <div ui-view="events">
        <div class="ct_event gapped bordered" ui-scroll="item in eventsDatasource" is-loading="$root.uiScroller.isLoading" adapter="adapter">
            <div ng-include="'views/partials/shortEvent.html'"></div>
        </div>

        <scroll-spinner></scroll-spinner>

        <div ng-if="eventsDatasource.hasMessage()">
            <div class="info box" ng-bind-html="eventsDatasource.getMessage()"></div>
        </div>
    </div>

## Controller
    'use strict';
    angular.module('regionApp.controllers').controller('EventsController', [
        '$scope', '$state', 'EventsDatasource',
        function($scope, $state, EventsDatasource) {

            $scope.eventsDatasource = EventsDatasource;
            var adapter = $scope.adapter = {};
        }
    ]);

## Spinner Directive

The spinner directive shows an overlay with a spinner until the datasource has finished loading the data.
Via the `is-loading` directive the `spinner`-directive gets informed when the datasource is finished.
This works when initially visiting the list view, but when coming back from a single view the `$watch` value does never change.

    'use strict';
    angular.module('regionApp.directives').directive('spinner', [
        '$rootScope', '$transitions',
        function($rootScope, $transitions) {
            return {
                restrict: 'E',
                compile: function(element) {
                    function showSpinner() {
                        element.show();
                    }

                    function hideSpinner() {
                        element.fadeOut('slow');
                    }

                    $transitions.onStart({}, showSpinner);
                    $transitions.onError({}, hideSpinner);

                    $rootScope.$watch('uiScroller.isLoading', function(newValue) {
                        if(newValue === false) {
                            hideSpinner();
                        }
                    });
                }
            };
        }
    ]);

**Comment by dhilt** [comment]
@tylkomat First of all, I've just released intermediate 1.6.3 version, which fixes 1.6.2 and makes us closer to 1.7.0. Not sure if it could help you, but it would be great if you try it. Also, the use case you described above requires non-trivial insfrastructe, and it will take a time to build it, and you may help us if you could make a reproducable demo of the issue on plunker, fiddler, or whatever (standalone zipped sources, git repo?).

**Comment by tylkomat** [comment]
1.6.3 works in that regard, but it seems `is-loading` and the `adapter` are not the same.

I have a function in the controller that stores the current index and when coming back reloads the datasource with the stored index. Due to the nature of `ui-router` the view gets destroyed, also the ui-view, and rebuild when coming back. The scope is still the same and not destroyed, but the `Adapter` is an empty object, or undefined if I don't initialize it.

Here the extended controller from before:

    'use strict';
    angular.module('regionApp.controllers').controller('EventsController', [
        '$scope', '$state', 'EventsDatasource',
        function($scope, $state, EventsDatasource) {
            $scope.eventsDatasource = EventsDatasource;
            $scope.adapter = {};

            $scope.getSetStartIndexCallback = function(item) {
                var topIndex = EventsDatasource.getIndex(item);

                return function() {
                    $scope.$watch('adapter', function(scopeAdapter) {
                        if(angular.isFunction(scopeAdapter.reload)) {
                            scopeAdapter.reload(topIndex < 0 ? 0 : topIndex);
                        }
                    });
                };
            };
        }
    ]);

I will try to create a demo.

**Comment by dhilt** [comment]
@tylkomat The ui-scroll creates and assigns the adapter object on the ui-scroll viewport's scope during ui-scroll directive's linking process. This occures when the view template renders. Of course there may be some uncertainty between ui-router call and ui-scroll adapter assignment. And there some ways to deal with it. Yes, the demo would be very helpful, cause I will be able to suggest an appropriate way without meta-level reasoning. Or to find a bug...

**Comment by tylkomat** [comment]
[Here](https://github.com/tylkomat/ui-scroll-router-example) is the demo. I think I managed to reduce it to the core. Don't wonder about the complexity, I kept the folder layout of the original app.

**Comment by dhilt** [comment]
@tylkomat I watched your demo, thanks for providing it! Right now I can't give an exhaustive answer, but I could suggest some good workaround. This is the problem of Adapter object assignment, and explicit Controller As syntax helps. Please check this PR: https://github.com/tylkomat/ui-scroll-router-example/pull/1.

**Comment by dhilt** [comment]
@tylkomat This is how $parse works. The ui-view directive injects intermediate scope between ListController' scope and local ui-scroll items scopes (since you have no ui-scroll-viewport). $parse service calculates adapter-attribute expression on the scope next to the ui-scroll. The ui-view' scope is a start point in target scope detecting. If you give to your adapter-attribute "my.adapter" value (not just "adapter") and define $scope.my = { adapter: {} } on you ListController' scope, then $parse will inject the Adapter object into the ListController' scope. This is what I did when I defined Controller As "List". The List property appeared on the ListController' scope and List.adapter target was located successfully by $parse.
